// using the refresh token generated by ms graph,
// returns a fresh access token that is good for like, 10 minutes or something

const fetch = require("node-fetch");
const toBody = require("./util/objectToParams");

global.Headers = fetch.Headers;

const refreshToken = async () => {
  const params = {
    grant_type: process.env.GRANT_TYPE,
    client_id: process.env.CLIENT_ID,
    client_secret: process.env.CLIENT_SECRET,
    scope: process.env.SCOPE
  };
  const token = await fetch(
    "https://login.microsoftonline.us/f5f47917-c904-4368-9120-d327cf175591/oauth2/v2.0/token",
    {
      method: "post",
      headers: new Headers({
        "Content-Type": "application/x-www-form-urlencoded"
      }),
      body: toBody(params)
    }
  );
  const response = await token.json();
  return response.access_token;
};

module.exports = refreshToken;
